"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 10:04:41.041203
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import raceforge.backend.db

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("token_id", sa.String(length=36), nullable=True),
        sa.Column("client", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_at"), "audit", ["at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("totp_secret", sa.String(length=64), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "blobs",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("sha256"),
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("used_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("used_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("client", sa.String(length=32), nullable=False),
        sa.Column("totp_verified", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_tokens_user_id"), "tokens", ["user_id"], unique=False)
    op.create_table(
        "uploads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("part_size", sa.BigInteger(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("completed_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "objects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("copied_from", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "slug"),
    )
    op.create_index(op.f("ix_objects_deleted_at"), "objects", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_objects_workspace_id"), "objects", ["workspace_id"], unique=False)
    op.create_table(
        "upload_parts",
        sa.Column("upload_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
        ),
        sa.PrimaryKeyConstraint("upload_id", "number"),
    )
    op.create_table(
        "drafts",
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("updated_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("object_id", "user_id"),
    )
    op.create_table(
        "versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("semver", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=36), nullable=False),
        sa.Column("created_at", raceforge.backend.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("parents", sa.JSON(), nullable=False),
        sa.Column("branch", sa.Boolean(), nullable=False),
        sa.Column("token_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["author"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_id", "semver"),
    )
    op.create_index(op.f("ix_versions_object_id"), "versions", ["object_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_versions_object_id"), table_name="versions")
    op.drop_table("versions")
    op.drop_table("drafts")
    op.drop_table("upload_parts")
    op.drop_index(op.f("ix_objects_workspace_id"), table_name="objects")
    op.drop_index(op.f("ix_objects_deleted_at"), table_name="objects")
    op.drop_table("objects")
    op.drop_table("workspaces")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_tokens_user_id"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_table("invites")
    op.drop_table("blobs")
    op.drop_table("users")
    op.drop_index(op.f("ix_audit_at"), table_name="audit")
    op.drop_table("audit")
    # ### end Alembic commands ###
