"""Spec 0011 AC1/AC3: EV3RT bridge: bundle schema, rf_config.h, build/upload, C host tests."""

import json
import shutil
import subprocess
from collections.abc import Sequence
from pathlib import Path

import httpx
import pytest
from pydantic import ValidationError

from raceforge import cli
from raceforge.car import ev3rt
from raceforge.car.bundle import (
    BundleManifest,
    Ev3Gains,
    Ev3Spec,
    RuntimeSpec,
    build_bundle,
)
from tests.car.test_bundle import ROBOT, TEMPLATES

ROOT = Path(__file__).resolve().parents[2]
CC = shutil.which("cc") or shutil.which("gcc") or shutil.which("clang")
MAKE = shutil.which("make")


def ev3rt_spec(**kw: object) -> Ev3Spec:
    base: dict[str, object] = {
        "steer_motor_deg_per_rad": 171.9,
        "drive_counts_per_m": 2046.0,
        "ultrasonic": {"front": "2", "left": "3"},
        "gyro_port": "4",
        "os": "ev3rt",
        "link": "uart",
    }
    return Ev3Spec.model_validate(base | kw)


def test_schema_rules() -> None:
    assert ev3rt_spec().device is None
    with pytest.raises(ValidationError, match="UART"):
        ev3rt_spec(ultrasonic={"front": "1"})  # port 1 is the link
    with pytest.raises(ValidationError, match="gyro_port"):
        ev3rt_spec(gyro_port=None)
    with pytest.raises(ValidationError, match="udp"):
        ev3rt_spec(os="ev3dev")  # ev3dev only talks UDP
    with pytest.raises(ValidationError, match="network"):
        ev3rt_spec(link="udp")
    assert ev3rt_spec(link="usb_cdc", ultrasonic={"front": "1"}).link == "usb_cdc"  # port 1 free


def test_bluetooth_link_refused_in_race_mode(tmp_path: Path) -> None:
    ev3 = ev3rt_spec(link="bt_spp")
    build_bundle(tmp_path / "t", TEMPLATES / "wall_follow.py", ROBOT, ev3)  # test mode: fine
    with pytest.raises(ValidationError, match="radios"):
        build_bundle(
            tmp_path / "r",
            TEMPLATES / "wall_follow.py",
            ROBOT,
            ev3,
            runtime=RuntimeSpec(mode="race"),
        )


def test_bundle_json_round_trip(tmp_path: Path) -> None:
    ev3 = ev3rt_spec(gains=Ev3Gains(steer_kp=2.0))
    build_bundle(tmp_path / "b", TEMPLATES / "wall_follow.py", ROBOT, ev3)
    raw = json.loads((tmp_path / "b" / "bundle.json").read_text())
    assert raw["ev3"]["os"] == "ev3rt" and raw["ev3"]["gains"]["steer_kp"] == 2.0
    assert BundleManifest.model_validate(raw).ev3 == ev3


def test_config_header_and_rc_conf() -> None:
    h = ev3rt.config_header(ev3rt_spec(estop_touch_port="1", link="usb_cdc"))
    assert "#define RF_LINK_PORT EV3_SERIAL_USB_CDC" in h
    assert "#define RF_SENSOR_1 RF_SENSOR_TOUCH" in h and "#define RF_ESTOP_TOUCH_PORT (0)" in h
    assert (
        "#define RF_SENSOR_2 RF_SENSOR_ULTRASONIC" in h
        and "#define RF_SENSOR_4 RF_SENSOR_GYRO" in h
    )
    assert "#define RF_STEER_PORT 0 /* A */" in h and "#define RF_DRIVE_PORT 1 /* B */" in h
    assert "#define RF_DRIVE_FF 0.09523809523809523f" in h
    assert "Mode=CDC" in ev3rt.rc_conf(ev3rt_spec(link="usb_cdc"))
    assert "DisablePort1=1" in ev3rt.rc_conf(ev3rt_spec())
    with pytest.raises(ev3rt.Ev3rtError):
        ev3rt.config_header(Ev3Spec(steer_motor_deg_per_rad=1, drive_counts_per_m=1))


def fake_sdk(tmp_path: Path) -> Path:
    sdk = tmp_path / "sdk"
    (sdk / "workspace").mkdir(parents=True)
    (sdk / "workspace" / "Makefile").write_text("# EV3RT workspace\n")
    return sdk


def test_build_stages_sources_and_runs_make(tmp_path: Path) -> None:
    sdk = fake_sdk(tmp_path)
    calls: list[tuple[list[str], Path]] = []

    def runner(cmd: Sequence[str], cwd: Path) -> int:
        calls.append((list(cmd), cwd))
        (cwd / "app").write_bytes(b"\x7fELF app")
        return 0

    app = ev3rt.build(sdk, ev3rt_spec(), runner=runner)
    staged = sdk / "workspace" / "raceforge_bridge"
    assert calls == [(["make", "app=raceforge_bridge"], sdk / "workspace")]
    assert app == sdk / "workspace" / "app"
    names = {p.name for p in staged.iterdir()}
    assert {
        "app.c",
        "app.cfg",
        "app.h",
        "Makefile.inc",
        "rf_proto.c",
        "rf_bridge.c",
        "rf_config.h",
    } <= names
    assert "Generated by" in (staged / "rf_config.h").read_text()

    def failing(cmd: Sequence[str], cwd: Path) -> int:
        return 2

    with pytest.raises(ev3rt.Ev3rtError, match="build failed"):
        ev3rt.build(sdk, ev3rt_spec(), runner=failing)
    with pytest.raises(ev3rt.Ev3rtError, match="EV3RT SDK"):
        ev3rt.build(tmp_path / "nope", ev3rt_spec(), runner=runner)


def test_upload_matches_ev3rt_make_upload(tmp_path: Path) -> None:
    app = tmp_path / "app"
    app.write_bytes(b"\x01\x02app")
    seen: list[httpx.Request] = []

    def handler(req: httpx.Request) -> httpx.Response:
        seen.append(req)
        return httpx.Response(200)

    ev3rt.upload(app, ip="10.0.10.1", client=httpx.Client(transport=httpx.MockTransport(handler)))
    [r] = seen
    assert str(r.url) == "http://10.0.10.1/upload" and r.content == b"\x01\x02app"
    assert r.headers["content-type"] == "ev3rt/app"
    assert r.headers["content-disposition"] == 'inline; filename="raceforge_bridge"'

    def refuse(req: httpx.Request) -> httpx.Response:
        return httpx.Response(500)

    with pytest.raises(ev3rt.Ev3rtError, match="refused"):
        ev3rt.upload(app, client=httpx.Client(transport=httpx.MockTransport(refuse)))

    def unreachable(req: httpx.Request) -> httpx.Response:
        raise httpx.ConnectError("no route")

    with pytest.raises(ev3rt.Ev3rtError, match="Bluetooth PAN"):
        ev3rt.upload(app, client=httpx.Client(transport=httpx.MockTransport(unreachable)))


def test_cli_config(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    build_bundle(tmp_path / "b", TEMPLATES / "wall_follow.py", ROBOT, ev3rt_spec())
    assert cli.main(["car", "ev3rt", "config", "--bundle", str(tmp_path / "b")]) == 0
    out = capsys.readouterr().out
    assert "RF_LINK_PORT EV3_SERIAL_UART" in out and "DisablePort1=1" in out
    assert (
        cli.main(
            ["car", "ev3rt", "build", "--bundle", str(tmp_path / "b"), "--sdk", str(tmp_path / "x")]
        )
        == 1
    )


@pytest.mark.skipif(CC is None or MAKE is None, reason="no C compiler / make")
def test_c_library_host_tests() -> None:
    """AC1: frames (golden, shared with Rust/Python), COBS, failsafe, e-stop, motor loops."""
    r = subprocess.run(
        [
            "make",
            "-C",
            str(ROOT / "ev3rt" / "tests"),
            "test",
            "CFLAGS=-std=c99 -O1 -Wall -Wextra -Werror",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert r.returncode == 0, r.stdout + r.stderr
    assert "all passed" in r.stdout


@pytest.mark.skipif(CC is None, reason="no C compiler")
def test_generated_config_compiles_with_the_app(tmp_path: Path) -> None:
    """The header Python writes is what app.c expects (checked against the stub EV3RT API)."""
    inc = tmp_path / "inc"
    inc.mkdir()
    (inc / "rf_config.h").write_text(
        ev3rt.config_header(ev3rt_spec(estop_touch_port="1", link="usb_cdc"))
    )
    r = subprocess.run(
        [
            CC or "cc",
            "-std=c99",
            "-Wall",
            "-Wextra",
            "-Werror",
            "-fsyntax-only",
            f"-I{inc}",
            f"-I{ROOT / 'ev3rt' / 'tests' / 'stub'}",
            f"-I{ROOT / 'ev3rt' / 'common'}",
            str(ROOT / "ev3rt" / "apps" / "raceforge_bridge" / "app.c"),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert r.returncode == 0, r.stderr
