/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/controllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Controllers */
        get: operations["controllers_api_v1_controllers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corridor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Corridor */
        post: operations["corridor_api_v1_corridor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parts */
        get: operations["parts_api_v1_parts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quickstart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quickstart */
        post: operations["quickstart_api_v1_quickstart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quickstart/export/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_v1_quickstart_export__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quickstart/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quickstart Schema */
        get: operations["quickstart_schema_api_v1_quickstart_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay */
        post: operations["replay_api_v1_replays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sim/protocol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sim Protocol
         * @description Message types of the /api/v1/sim WebSocket (documentation only).
         */
        get: operations["sim_protocol_api_v1_sim_protocol_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CarScene */
        CarScene: {
            /** Bodies */
            bodies: components["schemas"]["SceneBody"][];
            /** Name */
            name: string;
        };
        /** ControllerInfo */
        ControllerInfo: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Template */
            template: boolean;
        };
        /** CorridorParams */
        CorridorParams: {
            /**
             * Door Rate Per 10M
             * @default 0.8
             */
            door_rate_per_10m: number;
            /**
             * Friction Max
             * @default 0.9
             */
            friction_max: number;
            /**
             * Friction Min
             * @default 0.6
             */
            friction_min: number;
            /**
             * Glass Prob
             * @default 0.15
             */
            glass_prob: number;
            /**
             * Jog Rate Per 10M
             * @default 0.25
             */
            jog_rate_per_10m: number;
            /**
             * Length M
             * @default 60
             */
            length_m: number;
            /**
             * Loop
             * @default true
             */
            loop: boolean;
            /**
             * Niche Rate Per 10M
             * @default 1
             */
            niche_rate_per_10m: number;
            /**
             * Object Rate Per 10M
             * @default 0.6
             */
            object_rate_per_10m: number;
            /**
             * Pillar Rate Per 10M
             * @default 0.4
             */
            pillar_rate_per_10m: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Wall Height M
             * @default 2.5
             */
            wall_height_m: number;
            /**
             * Width Max M
             * @default 2.4
             */
            width_max_m: number;
            /**
             * Width Min M
             * @default 1.4
             */
            width_min_m: number;
        };
        /** CorridorResponse */
        CorridorResponse: {
            /** Centreline */
            centreline: [
                number,
                number
            ][];
            /** Primitives */
            primitives: components["schemas"]["Primitive"][];
            /** Track */
            track: {
                [key: string]: unknown;
            };
        };
        /** EgoView */
        EgoView: {
            /** Channels */
            channels: {
                [key: string]: number | boolean | string;
            };
            /** Distance M */
            distance_m: number;
            /** Finished */
            finished: boolean;
            /** Lap Times S */
            lap_times_s: number[];
            /** Laps */
            laps: number;
            /** Lidar Points */
            lidar_points: [
                number,
                number
            ][];
            /** Speed Cmd */
            speed_cmd: number;
            /** State */
            state: string;
            /** Steering Cmd */
            steering_cmd: number;
            /** Ultrasonic */
            ultrasonic: {
                [key: string]: components["schemas"]["UltrasonicView"];
            };
        };
        /** ErrorMessage */
        ErrorMessage: {
            /** Message */
            message: string;
            /**
             * Type
             * @default error
             * @constant
             */
            type: "error";
        };
        /** EventView */
        EventView: {
            /** Car */
            car: string;
            /** Kind */
            kind: string;
            /** Other */
            other: string;
            /** T */
            t: number;
        };
        /** FrameMessage */
        FrameMessage: {
            /** Bodies */
            bodies: {
                [key: string]: {
                    [key: string]: [
                        [
                            number,
                            number,
                            number
                        ],
                        [
                            number,
                            number,
                            number,
                            number
                        ]
                    ];
                };
            };
            ego: components["schemas"]["EgoView"];
            /** Events */
            events: components["schemas"]["EventView"][];
            /** T */
            t: number;
            /**
             * Type
             * @default frame
             * @constant
             */
            type: "frame";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Ldraw Available */
            ldraw_available: boolean;
            /** Ldraw Dir */
            ldraw_dir: string;
            /** Version */
            version: string;
        };
        /**
         * Layout
         * @enum {string}
         */
        Layout: "rwd" | "awd" | "fwd";
        /** PartSummary */
        PartSummary: {
            /** Category */
            category: string;
            /** Connectors */
            connectors: number;
            /** Device */
            device: string | null;
            /** Key */
            key: string;
            /** Ldraw Id */
            ldraw_id: string | null;
            /** Mass G */
            mass_g: number;
            /** Name */
            name: string;
            /** Verified */
            verified: boolean;
        };
        /** Primitive */
        Primitive: {
            /** Color */
            color: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "box" | "cylinder" | "plane";
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /** Pos */
            pos: [
                number,
                number,
                number
            ];
            /** Quat */
            quat: [
                number,
                number,
                number,
                number
            ];
            /** Size */
            size: [
                number,
                number,
                number
            ];
            /**
             * Surface
             * @default
             */
            surface: string;
        };
        /**
         * QuickStartParams
         * @description Inputs of the quick-start generator (spec 0002); invalid values list valid ones.
         */
        QuickStartParams: {
            /**
             * Ackermann Pct
             * @default 60
             */
            ackermann_pct: number;
            /**
             * Battery
             * @default powerbank
             * @enum {string}
             */
            battery: "powerbank" | "none";
            /**
             * Board
             * @default raspberry_pi_5
             * @enum {string}
             */
            board: "raspberry_pi_5" | "orange_pi_5" | "none";
            /**
             * Differential
             * @default true
             */
            differential: boolean;
            /** Drive Gears */
            drive_gears?: string | null;
            /**
             * Drive Motor
             * @default ev3_large
             * @enum {string}
             */
            drive_motor: "ev3_large" | "ev3_medium" | "dc_motor";
            /** @default rwd */
            layout: components["schemas"]["Layout"];
            /**
             * Max Steer Deg
             * @default 30
             */
            max_steer_deg: number;
            /** Measured Cog Mm */
            measured_cog_mm?: [
                number,
                number,
                number
            ] | null;
            /** Measured Mass Kg */
            measured_mass_kg?: number | null;
            /** Sensors */
            sensors?: components["schemas"]["SensorSpec"][];
            /**
             * Steering Motor
             * @default ev3_medium
             * @enum {string}
             */
            steering_motor: "ev3_medium" | "servo";
            /**
             * Steering Play Deg
             * @default 3
             */
            steering_play_deg: number;
            /**
             * Track Studs
             * @default 11
             */
            track_studs: number;
            /**
             * Wheel
             * @default 56908+55976
             */
            wheel: string;
            /**
             * Wheelbase Studs
             * @default 15
             */
            wheelbase_studs: number;
        };
        /** QuickstartResponse */
        QuickstartResponse: {
            /** Assembly */
            assembly: {
                [key: string]: unknown;
            };
            car: components["schemas"]["CarScene"];
            /** Derived */
            derived: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: components["schemas"]["Warning"][];
        };
        /** QuickstartSchema */
        QuickstartSchema: {
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Json Schema */
            json_schema: {
                [key: string]: unknown;
            };
            /** Options */
            options: {
                [key: string]: unknown[];
            };
        };
        /** ReplayRequest */
        ReplayRequest: {
            /** Path */
            path: string;
        };
        /** ReplaySummary */
        ReplaySummary: {
            /** Channels */
            channels: {
                [key: string]: (number | null)[];
            };
            /** Duration S */
            duration_s: number;
            /** Frames */
            frames: number;
            /** Speed Cmd */
            speed_cmd: number[];
            /** Speed Meas */
            speed_meas: (number | null)[];
            /** States */
            states: string[];
            /** Steering Cmd */
            steering_cmd: number[];
            /** T */
            t: number[];
            /** Truth Xy */
            truth_xy: [
                number,
                number
            ][];
        };
        /** ResultMessage */
        ResultMessage: {
            /** Finished */
            finished: boolean;
            /** Lap Times S */
            lap_times_s: number[];
            /** Laps */
            laps: number;
            /** Problems */
            problems: string[];
            /** Record Path */
            record_path: string | null;
            /** Sim Time S */
            sim_time_s: number;
            /**
             * Type
             * @default result
             * @constant
             */
            type: "result";
            /** Wall Contacts */
            wall_contacts: number;
        };
        /** SceneBody */
        SceneBody: {
            /** Name */
            name: string;
            /** Parts */
            parts: components["schemas"]["ScenePart"][];
        };
        /** SceneMessage */
        SceneMessage: {
            /** Cars */
            cars: components["schemas"]["CarScene"][];
            /** Centreline */
            centreline: [
                number,
                number
            ][];
            /** Primitives */
            primitives: components["schemas"]["Primitive"][];
            /**
             * Type
             * @default scene
             * @constant
             */
            type: "scene";
        };
        /** ScenePart */
        ScenePart: {
            /** Bbox Hi */
            bbox_hi: [
                number,
                number,
                number
            ];
            /** Bbox Lo */
            bbox_lo: [
                number,
                number,
                number
            ];
            /** Category */
            category: string;
            /** Color */
            color: number;
            /** Key */
            key: string;
            /** Ldraw Id */
            ldraw_id: string | null;
            /** Pos */
            pos: [
                number,
                number,
                number
            ];
            /** Quat */
            quat: [
                number,
                number,
                number,
                number
            ];
        };
        /** SensorSpec */
        SensorSpec: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "ev3_ultrasonic" | "ev3_gyro" | "ev3_touch" | "lidar_2d";
            /**
             * Offset Mm
             * @default [
             *       0,
             *       0,
             *       0
             *     ]
             */
            offset_mm: [
                number,
                number,
                number
            ];
            /**
             * Preset
             * @enum {string}
             */
            preset: "front" | "left" | "right" | "rear" | "center" | "top";
        };
        /** SimControl */
        SimControl: {
            /** Speed */
            speed?: number | null;
            /**
             * Type
             * @enum {string}
             */
            type: "pause" | "resume" | "stop" | "speed";
        };
        /**
         * SimProtocol
         * @description Documents the /api/v1/sim WebSocket messages so they appear in OpenAPI and the TS client.
         */
        SimProtocol: {
            client_control?: components["schemas"]["SimControl"] | null;
            client_start?: components["schemas"]["SimStart"] | null;
            server_error?: components["schemas"]["ErrorMessage"] | null;
            server_frame?: components["schemas"]["FrameMessage"] | null;
            server_result?: components["schemas"]["ResultMessage"] | null;
            server_scene?: components["schemas"]["SceneMessage"] | null;
        };
        /** SimStart */
        SimStart: {
            /** Controller */
            controller: string;
            corridor?: components["schemas"]["CorridorParams"];
            /**
             * Laps
             * @default 1
             */
            laps: number;
            /**
             * Opponents
             * @default 0
             */
            opponents: number;
            /** Params Path */
            params_path?: string | null;
            quickstart?: components["schemas"]["QuickStartParams"] | null;
            /** Record Path */
            record_path?: string | null;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Type
             * @default start
             * @constant
             */
            type: "start";
        };
        /** UltrasonicView */
        UltrasonicView: {
            /** Direction */
            direction: [
                number,
                number,
                number
            ];
            /** Origin */
            origin: [
                number,
                number,
                number
            ];
            /** Value */
            value: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Warning */
        Warning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    controllers_api_v1_controllers_get: {
        parameters: {
            query?: {
                extra?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControllerInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corridor_api_v1_corridor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorridorParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorridorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    parts_api_v1_parts_get: {
        parameters: {
            query?: {
                query?: string;
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quickstart_api_v1_quickstart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickStartParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickstartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v1_quickstart_export__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickStartParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quickstart_schema_api_v1_quickstart_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickstartSchema"];
                };
            };
        };
    };
    replay_api_v1_replays_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sim_protocol_api_v1_sim_protocol_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimProtocol"];
                };
            };
        };
    };
}
