"""EV3RT 1.1 bridge app: configure, build and upload (spec 0011).

The C sources live in ``ev3rt/`` (``common/`` shared library, ``apps/raceforge_bridge/`` the EV3RT
app). :func:`build` copies them into the EV3RT SDK's workspace together with an ``rf_config.h``
generated from the car bundle's ``ev3`` section and runs EV3RT's own ``make app=raceforge_bridge``.
:func:`upload` sends the resulting ``app`` file to the EV3RT loader over Bluetooth PAN, exactly like
EV3RT's ``make upload``.
"""

import shutil
import subprocess
from collections.abc import Callable, Sequence
from pathlib import Path

import httpx

from raceforge.car.bundle import Ev3Gains, Ev3Spec

APP = "raceforge_bridge"
DEFAULT_IP = "10.0.10.1"  # EV3RT's Bluetooth PAN address (NAP mode)
REPO_EV3RT = Path(__file__).resolve().parents[3] / "ev3rt"

_MOTOR = {"A": 0, "B": 1, "C": 2, "D": 3}
_LINK = {"uart": "EV3_SERIAL_UART", "usb_cdc": "EV3_SERIAL_USB_CDC", "bt_spp": "EV3_SERIAL_BT"}

Runner = Callable[[Sequence[str], Path], int]


class Ev3rtError(RuntimeError):
    pass


def sensor_kinds(ev3: Ev3Spec) -> list[str]:
    """RF_SENSOR_* name for ports 1..4."""
    kinds = ["RF_SENSOR_NONE"] * 4
    for port in ev3.ultrasonic.values():
        kinds[int(port) - 1] = "RF_SENSOR_ULTRASONIC"
    if ev3.gyro and ev3.gyro_port:
        kinds[int(ev3.gyro_port) - 1] = "RF_SENSOR_GYRO"
    if ev3.estop_touch_port:
        kinds[int(ev3.estop_touch_port) - 1] = "RF_SENSOR_TOUCH"
    return kinds


def _f(x: float) -> str:
    """C float literal (repr always has a '.' or an exponent)."""
    return f"{float(x)!r}f"


def config_header(ev3: Ev3Spec, steer_medium: bool = True) -> str:
    """``rf_config.h`` for the EV3RT bridge app from the bundle's EV3 section."""
    if ev3.os != "ev3rt":
        raise Ev3rtError('bundle ev3.os is not "ev3rt"')
    g = ev3.gains or Ev3Gains()
    kinds = sensor_kinds(ev3)
    estop = int(ev3.estop_touch_port) - 1 if ev3.estop_touch_port else -1
    lines = [
        "/* Generated by `raceforge car ev3rt build` from the car bundle (spec 0011). */",
        "#ifndef RF_CONFIG_H",
        "#define RF_CONFIG_H",
        "",
        "#define RF_CONTROL_PERIOD_MS 10",
        f"#define RF_LINK_PORT {_LINK[ev3.link]}",
        f"#define RF_STEER_PORT {_MOTOR[ev3.steer_motor]} /* {ev3.steer_motor} */",
        f"#define RF_DRIVE_PORT {_MOTOR[ev3.drive_motor]} /* {ev3.drive_motor} */",
        f"#define RF_STEER_MOTOR {'MEDIUM_MOTOR' if steer_medium else 'LARGE_MOTOR'}",
        "#define RF_DRIVE_MOTOR LARGE_MOTOR",
        *[f"#define RF_SENSOR_{i + 1} {k}" for i, k in enumerate(kinds)],
        f"#define RF_ESTOP_TOUCH_PORT ({estop})",
        "#define RF_FAILSAFE_MS 150",
        "",
        f"#define RF_DRIVE_FF {_f(g.drive_ff)}",
        f"#define RF_DRIVE_KP {_f(g.drive_kp)}",
        f"#define RF_DRIVE_KI {_f(g.drive_ki)}",
        f"#define RF_STEER_KP {_f(g.steer_kp)}",
        f"#define RF_STEER_MIN_POWER {g.steer_min_power}",
        f"#define RF_STEER_MAX_POWER {g.steer_max_power}",
        f"#define RF_STEER_DEADBAND_DEG {g.steer_deadband_deg}",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def rc_conf(ev3: Ev3Spec) -> str:
    """Settings the brick's ``/ev3rt/etc/rc.conf.ini`` needs for this link."""
    lines = ["[Debug]", "DefaultPort=LCD  ; keep log output off the link"]
    if ev3.link == "uart":
        lines += ["", "[Sensors]", "DisablePort1=1  ; sensor port 1 becomes the UART link"]
    if ev3.link == "usb_cdc":
        lines += ["", "[USB]", "Mode=CDC  ; USB port as virtual serial port"]
    if ev3.link == "bt_spp":
        lines += ["", "[Bluetooth]", "TurnOff=0  ; testing only: never in race mode"]
    return "\n".join(lines) + "\n"


def stage(sdk: Path, ev3: Ev3Spec, source: Path = REPO_EV3RT) -> Path:
    """Copy app, shared library and generated config to ``<sdk>/workspace/raceforge_bridge``."""
    workspace = sdk / "workspace"
    if not (workspace / "Makefile").is_file():
        raise Ev3rtError(f"{sdk} does not look like an EV3RT SDK (missing workspace/Makefile)")
    target = workspace / APP
    if target.exists():
        shutil.rmtree(target)
    target.mkdir()
    for f in sorted((source / "apps" / APP).iterdir()):
        if f.is_file() and f.name != "rf_config.h":
            shutil.copyfile(f, target / f.name)
    for f in sorted((source / "common").iterdir()):
        if f.suffix in (".c", ".h"):
            shutil.copyfile(f, target / f.name)
    (target / "rf_config.h").write_text(config_header(ev3), encoding="utf-8")
    return target


def _run(cmd: Sequence[str], cwd: Path) -> int:
    return subprocess.run(list(cmd), cwd=cwd, check=False).returncode


def build(sdk: Path, ev3: Ev3Spec, runner: Runner = _run, source: Path = REPO_EV3RT) -> Path:
    """Stage and run EV3RT's ``make app=raceforge_bridge``; returns the built ``app`` file."""
    stage(sdk, ev3, source)
    workspace = sdk / "workspace"
    code = runner(["make", f"app={APP}"], workspace)
    app = workspace / "app"
    if code != 0 or not app.is_file():
        raise Ev3rtError(f"EV3RT build failed (make exit code {code}); see the output above")
    return app


def upload(
    app_file: Path,
    ip: str = DEFAULT_IP,
    name: str = APP,
    client: httpx.Client | None = None,
) -> None:
    """Send the app to the EV3RT loader over Bluetooth PAN (same request as EV3RT's ``make
    upload``).
    """
    owned = client is None
    http = client or httpx.Client(timeout=30, trust_env=False)
    try:
        r = http.post(
            f"http://{ip}/upload",
            content=app_file.read_bytes(),
            headers={
                "Content-Type": "ev3rt/app",
                "Content-Disposition": f'inline; filename="{name}"',
            },
        )
    except httpx.TransportError as exc:
        raise Ev3rtError(
            f"EV3 not reachable at {ip}: connect this computer to the brick over Bluetooth PAN "
            "and start the EV3RT loader on the brick"
        ) from exc
    finally:
        if owned:
            http.close()
    if r.status_code >= 400:
        raise Ev3rtError(f"EV3RT loader refused the upload: HTTP {r.status_code}")
